project:
  type: website
  output-dir: docs   
  resources:
    - CNAME

website:
  title: "Dikran Meliksetian, Ph.D."

  navbar:
    background: white # Optional: Ensures text doesn't look messy scrolling behind it
    left:
      - href: index.html
        text: Home
      - href: teaching.html    
        text: Teaching       
      - href: blog.html
        text: Blog
      - href: patents.html
        text: Patents
      - href: publications.html
        text: Publications
    right:
      - icon: linkedin
        href: https://linkedin.com/in/your-profile
      - icon: github
        href: https://github.com/dmeliksetian
      - icon: envelope
        href: mailto:dikran.s.meliksetian@gmail.com




format:
  html:
    theme: cosmo
    title-block-banner: "#1e3a8a"
    title-block-banner-color: white
    toc: true
    page-layout: full
    css: styles.css
    include-after-body: footer.html
